[workspace]
authors = ["Saikari <lin@sz.cn.eu.org>"]
channels = ["conda-forge"]
name = "aui"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
build-docs = "mkdocs build --dirty"
serve-docs = "mkdocs serve --dirty"

[dependencies]
python = "3.14.*"
mkdocs = "1.6.*"
mkdocs-material = "9.6.*"
mkdocs-macros-plugin = "1.*"
mkdocs-gen-files = "0.*"
lunr = "0.*"
