name: Bug report
description: Create a report to help us improve
labels: ["bug"]
type: Bug
body:
  - type: checkboxes
    id: terms
    attributes:
      label: One More Step Before opening this issue
      description: |
        By submitting this issue, I'm agree:
      options:
        - label: To follow our [Code of Conduct](https://github.com/aui-framework/aui/blob/master/CODE_OF_CONDUCT.md)
          required: true
        - label: I've considered [existing issues on GitHub page](https://github.com/aui-framework/aui/issues) and didn't find a similar issue
          required: true

  - type: textarea
    id: issue
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output or stack trace
      description: |
        Please copy and paste any relevant log output.
        You can find log location by `CTRL+F` for `[UI thread][Logger][INFO]: Log file:` in your application output.
        Please remove any sensitive information before posting.
        Add the full stack trace if available.
        
        *This will be automatically formatted into code, so there is no need for backticks.*
      render: shell

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior – provide your build configuration.
      value: |
        1. Open `aui.example.views`
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Affected Platforms
      description: What platforms are you experiencing the problem on?
      multiple: true
      options:
        - Windows
        - Linux
        - macOS
        - Android
        - iOS
        - Emscripten

  - type: input
    id: url
    attributes:
      label: Link to build, i.e. failing GitHub Action job (if any).
      placeholder: https://github.com/username/project/actions/runs/1234567890
