#include <filesystem>
#include <functional>
#include <iostream>


#include "AUI/Common/AString.h"
#include "AUI/Common/AStringVector.h"
#include "AUI/Common/ByteBuffer.h"
#include "AUI/Common/AMap.h"
#include "AUI/IO/FileInputStream.h"
#include "AUI/IO/FileOutputStream.h"
#include "AUI/Util/BuiltinFiles.h"
#include "AUI/Util/LZ.h"

void printHelp()
{
	std::cout << "Available commands:" << std::endl
		<< "\tpack <dir> <dst>\t\tpack a dir into the .h file";
	exit(-1);
}

int main(int argc, char** argv)
{	
	std::cout << "Alex2772 Universal Interface toolbox" << std::endl;
	if (argc <= 1)
	{
		printHelp();
	}
	else
	{
		AStringVector args;
		for (int i = 2; i < argc; ++i)
		{
			args << argv[i];
		}

		AMap<AString, std::function<void()>> commands = {
			{
				"pack", [&]()
				{
					if (args.size() != 2)
					{
						printHelp();
					}
					else
					{
						
						try
						{
							ByteBuffer buffer;
							for (auto& entry : std::filesystem::recursive_directory_iterator(args[0].toStdString()))
							{
								if (entry.is_regular_file()) {
									try
									{
										AString filePath = AString::path(entry.path());
										filePath = filePath.replaceAll("\\", '/');
										
										buffer << filePath.toStdString();
										auto fis = _new<FileInputStream>(AString::path(entry.path()));

										ByteBuffer data;

										char buf[4096];
										for (int r; (r = fis->read(buf, sizeof(buf))) > 0;)
										{
											data.put(buf, r);
										}
										buffer << data.getSize();
										buffer << data;
										std::cout << ": packed " << filePath << std::endl;
									}
									catch (...)
									{
										std::cout << "Warning: could not read file " << entry.path() << std::endl;
									}
								}
							}

							ByteBuffer packed;
							LZ::compress(buffer, packed);

							AString name(
								std::filesystem::path(args[1].toStdString()).filename().wstring());

							auto dotPos = name.rfind(L'.');
							if (dotPos != AString::NPOS) {
								name = name.mid(0, dotPos - 1);
							}
							
							auto out = _new<FileOutputStream>(args[1]);
							*out << AString("#pragma once\n");
							*out << AString("// This file is autogenerated by AUI.Toolkit. Please do not modify.\n");
							*out << AString("const unsigned char AUI_PACKED_") << name << AString("[] = {");
							for (uint8_t c : packed)
							{
								char buf[32];
								sprintf(buf, "0x%02x,", c);
								*out << AString(buf);
							}
							*out << AString("};");
							std::cout << args[0] << " -> " << std::filesystem::absolute(args[1].toStdString()) << std::endl;
						}
						catch (...)
						{
							std::cout << "Could not open directory: " << std::filesystem::absolute(args[0].toStdString()) << std::endl;
							exit(-1);
						}
					}
				}
			}
		};
		if (auto c = commands.contains(argv[1]))
		{
			c->second();
		}
		else
		{
			printHelp();
		}
	}

	return 0;
}
