%% inaccurate!
flowchart BT
    gradle_gen --> gradle_build
    app.apk --> gradle_build

    gradle_build --> as["Android Studio"]

%% app.apk
    app.apk

    AUI --->|Template| gradle_gen

    arm64/libapp.so -->|CMake| app.apk
    armv7/libapp.so -->|CMake| app.apk

    AUI_arm64 --------->|aui.boot.cmake| arm64/libapp.so
    AUI_armv7 --------->|aui.boot.cmake| armv7/libapp.so

%% HOST
    AUI ---> auib_import
    subgraph cmake_cli[CMake CLI]
        cmake_configure["mkdir build && cd build && cmake .. -DAUI_BUILD_FOR=android"]
        cmake_build["cmake --build . -t apps"]
    end

    auib["aui.boot.cmake"] -->|download aui.boot| cmake_configure
    auib_import["auib_import(aui aui-framework/aui)"] -->|import aui| cmake_configure
    auib --> auib_import

    subgraph AUI["AUI (Host)"]
        direction LR
        aui.core.dll
        aui.views.dll
        aui.toolbox.exe
        gradle_project_template["Android project template"]
    end

    subgraph sys["System Libraries (Host)"]
        direction LR
        c++["C++ STD Lib"]
        sys_other[...]
    end

    subgraph aui_deps["AUI Dependencies (Host)"]
        direction LR
        ZLIB
        OpenSSL
        deps[...]
    end
    sys -->|find_package| AUI
    aui_deps --->|aui.boot.cmake| AUI

%% arm64
    subgraph AUI_arm64["AUI (arm64)"]
        direction LR
        libaui.core.a_arm64["libaui.core.a"]
        libaui.views.a_arm64["libaui.views.a"]
        libaui_other_arm64["..."]
    end

    subgraph sys_arm64["System Libraries (arm64)"]
        direction LR
        c++_arm64["C++ STD Lib"]
        sys_other_arm64[...]
    end

    subgraph aui_deps_arm64["AUI Dependencies (arm64)"]
        direction LR
        ZLIB_arm64[ZLIB]
        OpenSSL_arm64[OpenSSL]
        deps_arm64[...]
    end
    sys_arm64 -->|find_package| AUI_arm64
    aui_deps_arm64 --->|aui.boot.cmake| AUI_arm64
    icon.svg.cpp -->|"C++ compiler (arm64)"| arm64/libapp.so
    main.cpp -->|"C++ compiler (arm64)"| arm64/libapp.so

%% armv7
    subgraph AUI_armv7["AUI (armv7)"]
        direction LR
        libaui.core.a_armv7["libaui.core.a"]
        libaui.views.a_armv7["libaui.views.a"]
        libaui_other_armv7["..."]
    end

    subgraph sys_armv7["System Libraries (armv7)"]
        direction LR
        c++_armv7["C++ STD Lib"]
        sys_other_armv7[...]
    end

    subgraph aui_deps_armv7["AUI Dependencies (armv7)"]
        direction LR
        ZLIB_armv7[ZLIB]
        OpenSSL_armv7[OpenSSL]
        deps_armv7[...]
    end
    sys_armv7 -->|find_package| AUI_armv7
    aui_deps_armv7 --->|aui.boot.cmake| AUI_armv7
    main.cpp -->|"C++ compiler (armv7)"| armv7/libapp.so
    icon.svg.cpp ---->|"C++ compiler (armv7)"| armv7/libapp.so

    ass_conv[convert icon.svg to icon.svg.cpp] --> icon.svg.cpp
    assets/icon.svg --> ass_conv
    AUI ----->|aui.toolbox.exe | ass_conv

    gradle_gen["Generate Gradle Project"] --> cmake_build
    gradle_build["./gradle build"] --> cmake_build
