flowchart BT
    subgraph ide["User's IDE (optional)"]
        CLion
        VSCode
    end

    subgraph cmake_cli[CMake CLI]
        cmake_configure["mkdir build && cd build && cmake .."]
        cmake_build["cmake --build . -t app"]
    end

    cmake_cli --> ide

    auib["aui.boot.cmake"] -->|download aui.boot| cmake_configure
    auib_import["auib_import(aui aui-framework/aui)"] -->|import aui| cmake_configure
    auib ---> auib_import

    subgraph AUI
        aui.core.dll
        aui.views.dll
        aui_other["..."]
        aui.toolbox.exe
    end

    subgraph sys["System Libraries"]
        direction LR
        c++["C++ STD Lib"]
        sys_other[...]
    end

    subgraph aui_deps["AUI Dependencies"]
        direction LR
        ZLIB
        OpenSSL
        deps[...]
    end
    sys -->|find_package| AUI
    aui_deps -->|aui.boot.cmake| AUI

    AUI ---> auib_import
    AUI ---> app.exe
    app.exe --> cmake_build
    main.cpp -->|C++ compiler| app.exe
    icon.svg.cpp -->|C++ compiler| app.exe
    ass_conv[convert icon.svg to icon.svg.cpp] --> icon.svg.cpp
    aui.toolbox.exe ---> ass_conv
    assets/icon.svg --> ass_conv
