/*
 * AUI Framework - Declarative UI toolkit for modern C++20
 * Copyright (C) 2020-2025 Alex2772 and Contributors
 *
 * SPDX-License-Identifier: MPL-2.0
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

#pragma once

#include <AUI/Common/AObject.h>
#include <AUI/Common/ASignal.h>
#include "ObjectLoader.h"


/**
 * @brief Hot code reload and rapid development
 * @details
 * The development workflow for UI applications can be repetitive and slow, commonly requiring you to:
 *
 * 1. Write or modify code.
 * 2. Compile.
 * 3. Run the application.
 * 4. Navigate to the affected UI or feature.
 * 5. Check for expected results.
 * 6. Repeat as needed.
 *
 * Steps `2-5` are very slow and exhausting. This page briefly describes ways to reduce turnaround time during
 * development of your application.
 *
 * ## Precompiled Headers
 *
 * Precompiled headers (PCH) can significantly speed up C++ compilation by parsing common headers only once.
 * They are especially beneficial for large projects with many dependencies.
 *
 * **How to use precompiled headers with CMake**:
 *
 * - Create a header file (e.g. `pch.h`) containing your frequently used includes:
 *
 *    ```cpp title="pch.h"
 *    #include <AUI/Platform/AWindow.h>
 *    #include <AUI/Util/UIBuildingHelpers.h>
 *    // Add other common headers here
 *    ```
 *
 * - In your `CMakeLists.txt`:
 *
 *    ```cmake title="CMakeLists.txt"
 *    # CMake 3.16 or newer recommended for target_precompile_headers
 *    add_library(my_target ...)
 *    target_precompile_headers(my_target PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/pch.h")
 *    ```
 *
 * Make sure all source files include `pch.h` (either directly or via your main header). For more complex setups, review
 * CMake’s documentation on precompiled headers.
 *
 * ## The AHotCodeReload Class
 *
 * `AHotCodeReload` enables runtime reloading of object files, injecting new function code into a live application.
 * This gives rapid feedback and reduces iteration time during development.
 *
 * | Platform     | Supported |
 * | ------------ | --------- |
 * | Windows      | No        |
 * | Linux        | Yes       |
 * | macOS        | No        |
 * | Android      | No        |
 * | iOS          | No        |
 *
 * It works by observing changes on object files, which are generated by compiler and picked up by linker.
 * AHotCodeReload implements its own linker designed specifically to load these intermediate build files and link them
 * against a program which is already running. Then, it scans for newly loaded functions and places hooks on old
 * versions of these functions, so the newer version is called.
 *
 * Unlike classic way of implementing hot code reload with dynamic libraries, approach implemented in AUI does not
 * interfere with build process nor require special project structure with complicated state management. It does not
 * replace older symbols with newer ones, it keeps them both in memory, so referencing both is safe.
 *
 * ### Usage
 *
 * 1. Launch your application.
 * 2. Edit your source code.
 * 3. Compile. (You may skip the linking step.)
 * 4. Wait for patching to complete.
 * 5. Repeat steps 2–4 as needed.
 *
 * ### Limitations
 *
 * 1. `AHotCodeReload` performs some safety checks, but a patch could still break your application.
 * 2. Only function code is updated. Changes to static/global non-constant variables are not reinitialized and will not
 *    take effect. Constants (such as string literals) will be updated.
 * 3. For changes to take effect, the patched functions must be called (e.g. by re-triggering the relevant UI action).
 * 4. Do not modify struct or class layouts; the system cannot reliably detect or adjust for such changes.
 *
 * ## Best Practices
 *
 * - Use hot code reloading for iterative development on function logic and UI changes.
 * - Do not rely on this system for data or memory layout changes.
 * - Consider combining hot reload with precompiled headers to further minimize turnaround time.
 */
class API_AUI_REMOTE_TOOLS AHotCodeReload : public AObject {
public:
    AHotCodeReload();
    ~AHotCodeReload();
    static AHotCodeReload& instance() {
        static AHotCodeReload instance;
        return instance;
    }

    void reload();

    emits<> patchBegin;
    emits<> patchEnd;

private:
    ObjectLoader mLoader;

};
